baseURL = "/"
relativeURLs = true
locale = "en"
title = "Seabird Conference 2027"
defaultContentLanguage = "en"

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true