[params]
  displayName = "EN"
  isoCode = "en"
  weight = 1
  languageDirection = "ltr"
  title = "Gdansk 2027"
  description = "A developer conference in the heart of Gdansk, Poland — June 14, 2027"
