colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = false

defaultBackgroundImage = "images/background.jpg"

[homepage]
  layout = "background"
  showRecent = false

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = false

[article]
  showDate = false
  showAuthor = false
  showReadingTime = false
  showTableOfContents = false
  showWordCount = false
