colorScheme = "ocean"
customCSS = ["css/custom.css"]
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = false

[homepage]
  layout = "custom"
  showRecent = false

[header]
  layout = "basic"
    logo = "images/header-logo.png"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false

[article]
  showDate = false
  showAuthor = false
  showReadingTime = false
  showTableOfContents = false
  showWordCount = false
